# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
  - repo: self
variables:
  imagePullSecret: 'regcred'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    steps:
   
    - task: Docker@2
      inputs:
        containerRegistry: 'matrix-docker'
        repository: 'take-a-guide/backend'
        command: 'buildAndPush'
        tags: '$(Build.BuildId)'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'