spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  application:
    name: take-a-guide

springdoc:
  swagger-ui:
    path: "/api-docs"

server:
  port: 8081

azure:
  servicebus:
    namespace: ${AZURE_SERVICEBUS_NAMESPACE}
    connection-string: ${AZURE_SERVICEBUS_CONNECTION_STRING}
    queue-name: ${AZURE_SERVICEBUS_QUEUE_NAME}
    QueueName: ${AZURE_SERVICEBUS_QUEUE_NAME}
